[package]
name = "explain"
version = "0.1.0"
authors = ["Sanpi <sanpi@homecomputing.fr>"]
edition = "2018"

[dependencies]
lazy_static = "1.4"
serde_json = "1.0"
structopt = "0.3"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.postgres]
version = "0.17"
features = ["with-serde_json-1"]
